ALTER TABLE orders ADD COLUMN IF NOT EXISTS reservation_code VARCHAR(255) UNIQUE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receipt_url VARCHAR(255);