@baseURL = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiZWRtaWx6b24ubHVuYUBnbWFpbC5jb20iLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzc5NDUwOTIxLCJleHAiOjE3Nzk1MzczMjF9.YpYVQCpuZkmcL6pn3XSPDwbuFvQLPTXZssAVKVVp6vE

### Registrar cliente (rol CLIENT por defecto)
POST {{baseURL}}/auth/register
Content-Type: application/json

{
  "name": "Edmilzon Luna",
  "email": "edmilzon.luna@gmail.com",
  "password": "Edmilzon_890"
}
# Respuesta: { user: { id, email, role, name }, access_token }

### Registrar comerciante (rol MERCHANT + crea comercio)
POST {{baseURL}}/auth/register-commerce
Content-Type: application/json

{
  "ownerName": "Juan Perez",
  "email": "tienda@example.com",
  "password": "password123",
  "commerceName": "Panadería Don Juan",
  "description": "Panadería fresca",
  "latitude": -16.5,
  "longitude": -68.15,
  "nit": "123456789"
}
# Respuesta: { user: { id, email, role, name }, commerce: { id, name }, access_token }

### Iniciar sesión (MERCHANT incluye datos del comercio)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "edmilzon.luna@gmail.com",
  "password": "Edmilzon_890"
}
# Respuesta: { user: { id, email, name, role }, access_token }

### Obtener perfil del usuario autenticado (MERCHANT incluye comercio)
GET {{baseURL}}/auth/me
Authorization: Bearer {{token}}
# Respuesta: { user: { id, email, name, role } } (+ commerce si MERCHANT)

### Cerrar sesión (solo indica al cliente eliminar token local)
POST {{baseURL}}/auth/logout
Authorization: Bearer {{token}}
# Respuesta: { message }
